### ISSUE TITLE
Comment on the blog post

### ISSUE THREAD

**Issue by tvaranka** [tilman151/composing-datasets#1]
Hey, just wanted to say I really enjoyed the read. Been lately looking into solving a similar problem of exploding number of different datasets due to the use of inheritance and composition seems the way to go.

However, I am wondering if there is a downside to this. To construct a new dataset using composition this is the line being used.
```python
TextClassificationDataset(HateSpeechDataset(),
                          lambda x: revtok.tokenize(x, split_punctuation=True))
```
In my opinion it is rather complex compared to the inheritance case
```python
HateSpeechDataset("revtok")
```
This may not be an issue when you are familiar with the code base, but what about when we have an API. For new users not familiar with the code base this adds complexity that may refrain the use. Are we moving the complexity from the implementation to the user? Could we build another layer on top of the composition solution to make it easier to use?

Would love to hear your thoughts, thanks!

**Comment by tilman151** [comment]
Hey, thanks for your comment. I see what you mean. I think my solution here would be to create factory functions for common use cases:

```python
def hate_speech_dataset(task, tokenizer):
    if task == "classification":
        dataset = TextClassificationDataset(HateSpeechDataset(), tokenizer)
    elif ...

    return dataset
```

This makes the API easy for the common use cases while retaining flexibility and extensibility for advanced users. It is not perfect but, in my opinion, preferable to maintaining this big inheritance tree.

**Comment by tvaranka** [comment]
I like this solution! It adds the ease of use with the cost of few added functions. As you said it's not perfect, but I do agree that this is probably the best solution for most cases.

Thanks!
